version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ndne
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./tsconfig.json:/tsconfig.json:ro
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
    environment:
      DB_URL: postgres://user:pass@postgres:5432/ndne
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret
      OPENROUTER_API_KEY: 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
      CORS_ORIGINS: http://localhost:5173,http://localhost:5174
      # Discourse API Settings
      DISCOURSE_URL: ${DISCOURSE_URL:-http://localhost:3000}
      DISCOURSE_API_KEY: ${DISCOURSE_API_KEY:-your_discourse_api_key}
      DISCOURSE_API_USERNAME: ${DISCOURSE_API_USERNAME:-system}
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
volumes:
  pgdata:
