version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ndne
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./tsconfig.json:/tsconfig.json:ro
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
    environment:
      DB_URL: postgres://user:pass@postgres:5432/ndne
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret
      CORS_ORIGINS: http://localhost:5173,http://localhost:5174
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
volumes:
  pgdata:
